package dk.kvalitetsit.itukt.repository.entity;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.time.LocalDateTime;

public record PackingEnitity(
        LocalDateTime validto,
        Long varenummer,
        String alfabetsekvensnr,
        BigDecimal antaldddprpakning,
        Long antaldelpakninger,
        String beregningskodeairegpris,
        String datoforsenesteprisaendring,
        byte dosisdispenserbar,
        Long drugid,
        String emballagetypekode,
        Long faerdigfremstillingsgebyr,
        String klausuleringskode,
        Timestamp LastReplicated,
        String medicintilskudskode,
        String opbevaringsbetingelser,
        Long opbevaringstid,
        Long opbevaringstidnumerisk,
        String oprettelsesdato,
        Long pakningoptagetitilskudsgruppe,
        Long pakningpid,
        Long pakningsdistributoer,
        BigDecimal pakningsstoerrelsenumerisk,
        String pakningsstoerrelsesenhed,
        String pakningsstoerrelsetekst,
        String udgaaetdato,
        String udleveringsbestemmelse,
        String udleveringspeciale,
        LocalDateTime validfrom,
        Long varenummerdelpakning
) {}
