openapi: 3.0.1
info:
  title: Validation Component
  description: ""
  version: "1.0.0"
  contact:
    email: "development@kvalitetitsit.dk"
tags:
  - name: management
    description: "the API needed in order to manage clauses"
servers:
  - url: '{protocol}://{environment}:{port}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      environment:
        enum:
          - localhost # Docker-compose setup
        default: localhost # Development
      port:
        enum:
          - "8080"
        default: "8080"
paths:
  /2025/08/01/clauses/dsl:
    post:
      tags:
        - management
      requestBody:
        description: "A clause in Domain-Specific Language (DSL) format"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DslInput'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DslOutput'
        '400':
          $ref: '#/components/responses/400'
    get:
      tags:
        - management
      description: "Retrieves all clauses as dsl"
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DslOutput'
        '400':
          $ref: '#/components/responses/400'

  /2025/08/01/clauses/dsl/{id}:
    get:
      tags:
        - management
      summary: "Retrieves the clause associated with the specified id "
      description: "Retrieves the clause associated with the specified id"
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DslOutput'
            text/plain:
              schema:
                type: string
        '400':
          $ref: '#/components/responses/400'

  /2025/08/01/clauses:
    post:
      tags:
        - management
      requestBody:
        description: "A list of expressions"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClauseInput'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClauseOutput'
        '400':
          $ref: '#/components/responses/400'


    get:
      tags:
        - management
      summary: "API to test body validation"
      description: "Retrieves all clauses"
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClauseOutput'
            text/plain:
              schema:
                type: string
        '400':
          $ref: '#/components/responses/400'

  /2025/08/01/clauses/{name}:
    put:
      tags:
        - management
      summary: "Update clause"
      description: "Creates a new version of the clause matching the specified name"
      parameters:
        - $ref: '#/components/parameters/name'
      requestBody:
        description: "A list of expressions"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClauseUpdateInput'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClauseOutput'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'

  /2025/08/01/clauses/{id}:
    get:
      tags:
        - management
      summary: "Retrieves the clause associated with the specified id"
      description: "Retrieves the clause associated with the specified id"
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClauseOutput'
            text/plain:
              schema:
                type: string
        '400':
          $ref: '#/components/responses/400'

components:
  responses:
    '400':
      description: "Bad Request. This could be because: * One of the required parameters/properties are missing or is empty <br> * Length of input is exceeding maximum length <br> (See a possible detailed error message in the in the response.)"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/detailedError'
    '401':
      description: "Unauthorized. This could be because: <br> * The calling system has not been properly authenticated."
    '403':
      description: "Forbidden. This could be because: <br> * The requested information does not belong the organisation of the user <br> * The calling user does not have the required roles"
    '404':
      description: "Not found. The requested resource could not be found."

  parameters:
    id:
      name: id
      in: path
      description: a clause id in uuid format.
      required: true
      schema:
        type: string
        format: uuid
    name:
      name: name
      in: path
      description: a clause name.
      required: true
      schema:
        type: string
    offset:
      name: offset
      in: query
      schema:
        type: integer
      description: The zero-based index from which to start returning results
    limit:
      name: limit
      in: query
      schema:
        type: integer
      description: The maximum number of items to retrieve. Used together with the 'offset' parameter to control pagination.

  schemas:
    detailedError:
      allOf:
        - $ref: './common.yaml#/components/schemas/basicError'
        - type: object
          required:
            - detailed_error
            - detailed_error_code
          properties:
            detailed_error:
              description: Detailed error text. This could be a text describing an validation error.
              type: string
            detailed_error_code:
              description: >-
                Detailed error code. This could be a code describing a validation error.
                <ul>
                  <li>1: Bad request</li>
                  <li>2: Not found</li>
                </ul>
              type: string
              enum:
                - "1"
                - "2"
    ClauseInput:
      type: object
      required:
        - name
        - expression
        - error
      properties:
        name:
          type: string
          description: "The name of the clause"
          example: "CHOL"
        expression:
          $ref: '#/components/schemas/Expression'
        error:
          $ref: './common.yaml#/components/schemas/ErrorMessage'

    ClauseUpdateInput:
      type: object
      required:
        - expression
        - error
      properties:
        expression:
          $ref: '#/components/schemas/Expression'
        error:
          $ref: './common.yaml#/components/schemas/ErrorMessage'

    ClauseOutput:
      allOf:
        - $ref: "#/components/schemas/ClauseInput"
        - type: object
          required:
            - uuid
          properties:
            uuid:
              type: string
              format: uuid
              description: an unique id which addresses the single clause
              example: 3d1006d3-3d2a-4361-b9b2-8f255d2aeaae
            error:
              $ref: './common.yaml#/components/schemas/ErrorMessage'

    Expression:
      type: object
      description: "A polymorphic interface that represents an expression. It can be a condition or a binary expression combining other expressions"
      oneOf:
        - $ref: '#/components/schemas/IndicationCondition'
        - $ref: '#/components/schemas/AgeCondition'
        - $ref: '#/components/schemas/ExistingDrugMedicationCondition'
        - $ref: '#/components/schemas/BinaryExpression'
        - $ref: '#/components/schemas/DoctorSpecialityCondition'
      discriminator:
        propertyName: type
        mapping:
          IndicationCondition: '#/components/schemas/IndicationCondition'
          AgeCondition: '#/components/schemas/AgeCondition'
          ExistingDrugMedicationCondition: '#/components/schemas/ExistingDrugMedicationCondition'
          BinaryExpression: '#/components/schemas/BinaryExpression'
          DoctorSpecialityCondition: '#/components/schemas/DoctorSpecialityCondition'

    Operator:
      description: "The operator used in a number condition"
      type: string
      example: "<="
      enum:
        - "="
        - ">="
        - "<="
        - ">"
        - "<"

    BinaryOperator:
      description: "The binary operator (e.g., 'AND', 'OR') connecting the two expressions"
      type: string
      example: "AND"
      enum:
        - "AND"
        - "OR"

    IndicationCondition:
      description: "A basic condition consisting of a field and a string value. This represents the most atomic form of an expression"
      type: object
      required: [ type, value ]
      properties:
        value:
          description: "The value, that the field is compared against"
          type: string
        type:
          type: string
          description: "Identifies this object as a IndicationCondition expression"
          example: "IndicationCondition"

    DoctorSpecialityCondition:
      description: "A basic condition consisting of a field and a string value. This represents the most atomic form of an expression"
      type: object
      required: [ type, value ]
      properties:
        value:
          description: "The value that the field is compared against"
          type: string
        type:
          type: string
          description: "Identifies this object as a DoctorSpecialityCondition expression"
          example: "DoctorSpecialityCondition"

    AgeCondition:
      description: "A basic condition consisting of a field, an operation and a number value. This represents the most atomic form of an expression"
      type: object
      required: [ type, operator, value ]
      properties:
        operator:
          $ref: '#/components/schemas/Operator'
        value:
          description: "The value, that the field is compared against"
          type: integer
        type:
          type: string
          description: "Identifies this object as a AgeCondition expression"
          example: "AgeCondition"

    ExistingDrugMedicationCondition:
      description: "A condition for existing drug medication"
      allOf:
        - $ref: "./common.yaml#/components/schemas/ExistingDrugMedication"
        - type: object
          required:
            - type
          properties:
            type:
              type: string
              description: "Identifies this object as a ExistingDrugMedicationCondition expression"
              example: "ExistingDrugMedicationCondition"

    BinaryExpression:
      description: "A compound expression combining two expressions with a binary operator such as AND or OR"
      type: object
      required: [ type, left, operator, right ]
      properties:
        left:
          description: "The left-hand side expression"
          $ref: '#/components/schemas/Expression'
        operator:
          $ref: '#/components/schemas/BinaryOperator'
        right:
          description: "The right-hand side expression."
          $ref: '#/components/schemas/Expression'
        type:
          type: string
          description: "Identifies this object as a BinaryExpression"
          example: "BinaryExpression"

    DslInput:
      type: object
      required:
        - dsl
        - error
      properties:
        error:
          $ref: './common.yaml#/components/schemas/ErrorMessage'
        dsl:
          $ref: '#/components/schemas/Dsl'

    DslOutput:
      allOf:
        - $ref: "#/components/schemas/DslInput"
        - type: object
          required:
            - uuid
          properties:
            uuid:
              type: string
              description: An unique id which is used to address a single clause
              format: uuid
              example: 3d1006d3-3d2a-4361-b9b2-8f255d2aeaae
            error:
              $ref: './common.yaml#/components/schemas/ErrorMessage'

    Dsl:
      description: "A clause specified in a domain specific language (DSL)"
      type: string
      #      pattern: "^\\s*(?:(Klausul|og|eller)|(>=|<=|=|i)|([A-Za-z][A-Za-z0-9]*)|([0-9]+)|([:,()])|(\\S))"
      example: "Klausul CHOL: ALDER >= 13 og EKSISTERENDE_LÆGEMIDDEL = {ATC = *, FORM = TABLET, ROUTE = *} og SPECIALE = psyk"