openapi: 3.0.1
info:
  title: Validation Component
  description: ""
  version: "1.0.0"
  contact:
    email: "development@kvalitetitsit.dk"
tags:
  - name: validation
    description: "API til at validere lægemiddelordinationer fra FMK (fælles medicin kort)"
servers:
  - url: '{protocol}://{environment}:{port}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      environment:
        enum:
          - localhost # Docker-compose setup
        default: localhost # Development
      port:
        enum:
          - "8080"
        default: "8080"
paths:
  /2025/08/01/validate:
    post:
      tags:
        - validation
      description: "Validerer lægemiddelordinationener fra FMK"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/validationRequest'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/validationResponse'
            text/plain:
              schema:
                type: string
        '400':
          $ref: '#/components/responses/400'

components:
  responses:
    '400':
      description: "Bad Request"
      content:
        application/json:
          schema:
            $ref: './common.yaml#/components/schemas/basicError'

  schemas:
    validationRequest:
      type: object
      required:
        - skipValidations
        - personIdentifier
        - age
        - validate
      properties:
        skipValidations:
          description: "Koder for fejltyper som skal tilsidesættes ved validering"
          type: array
          items:
            $ref: "#/components/schemas/ErrorCode"
        personIdentifier:
          description: "Unikt id svarende til CPR medicinkortets id, CPR-nummer eller eCPR-nummer, disse værdier medsendes ikke, da data i kaldet dermed er pseudonymiseret. Det skal være muligt at finde tilbage til CPR-nummer eller eCPR-nummer ved opslag i FMK, f.eks. ved fejlsøgning"
          type: string
          example: "1234567890"
        age:
          description: "Patientens/borgerens alder"
          type: integer
          example: 62
          minimum: 0
        validate:
          description: "Data der skal valideres"
          type: array
          items:
            $ref: "#/components/schemas/validate"
        existingDrugMedications:
          description: "Eksisterende lægemiddelordinationer i FMK. En tom liste betyder at sådanne data ikke findes. Mangler feltet, er data bevidst ikke sendt med"
          type: array
          nullable: true
          items:
            $ref: "#/components/schemas/ExistingDrugMedicationInput"


    validate:
      description: "Data der skal valideres"
      type: object
      required:
        - action
        - elementPath
        - newDrugMedication
      properties:
        action:
          description: "Handlingen der kræver validering"
          type: string
          enum:
            - CreateDrugMedication
            - UpdateDrugMedication
            - CreatePrescription
          example: CreateDrugMedication
        elementPath:
          description: "FMK’s element path i udvidet valideringer"
          type: string
          example: CreateDrugMedicationRequest.DrugMedication[2]
        newDrugMedication:
            $ref: "#/components/schemas/newDrugMedication"

    newDrugMedication:
      description: "Data fra lægemiddelordinationen som skal valideres"
      type: object
      required:
        - createdBy
        - createdDateTime
        - drugIdentifier
        - indicationCode
      properties:
        createdBy:
          description: "Aktør der har oprettet lægemiddelordinationen"
          $ref: "#/components/schemas/actor"
        reportedBy:
          description: "Aktør der har rapporteret lægemiddelordinationen"
          $ref: "#/components/schemas/actor"
        createdDateTime:
          description: "Dato og tid for oprettelse af lægemiddelordinationen"
          type: string
          format: date-time
          example: "2025-06-13T14:24:03+02:00"
        drugIdentifier:
          $ref: "#/components/schemas/drugIdentifier"
        indicationCode:
          description: "Indikationen som angivet ved oprettelse af ordinationen. Kilde er altid Medicinpriser"
          type: string
          example: "31"

    drugIdentifier:
      description: "Lægemidlets drugid. Kilde er foreløbigt altid Medicinpriser"
      type: long
      example: "28100902676"

    actor:
      description: "Aktør for lægemiddelordinationen"
      type: object
      required:
        - identifier
      properties:
        identifier:
          description: "Unikt id for aktøren"
          type: string
          example: "123456"
        specialityCode:
          description: "Lægens speciale jf. autorisationsregistret"
          type: string
          example: "PSYK"
        organisationIdentifier:
          $ref: "#/components/schemas/organisationIdentifier"

    organisationIdentifier:
      required:
        - code
        - type
      description: "Organisationens SOR eller SHAK kode"
      properties:
        code:
          description: "Den konkrete kode om det måtte være SOR eller SHAK"
          type: string
          example: "950731000016005"
        type:
          description: "Typen af identifier"
          type: string
          example: "SOR"
          enum:
            - SOR
            - SHAK

    ExistingDrugMedicationInput:
      description: "Udvalgte data for lægemiddelordinationer i FMK, inklusiv tidligere versioner"
      allOf:
        - $ref: "./common.yaml#/components/schemas/ExistingDrugMedication"
        - type: object
          required:
            - drugIdentifier
          properties:
            drugIdentifier:
              $ref: "#/components/schemas/drugIdentifier"

    validationResponse:
      type: object
      oneOf:
        - $ref: '#/components/schemas/validationSuccess'
        - $ref: '#/components/schemas/validationNotPossible'
        - $ref: '#/components/schemas/validationFailed'
      discriminator:
        propertyName: validationStatus
        mapping:
          validationSuccess: '#/components/schemas/validationSuccess'
          validationNotPossible: '#/components/schemas/validationNotPossible'
          validationFailed: '#/components/schemas/validationFailed'

    validationSuccess:
      description: "Valideringen er gennemført uden fejl. validationStatus=validationSuccess"
      type: object
      required:
        - validationStatus
      properties:
        validationStatus:
            type: string

    validationNotPossible:
      description: "Valideringen kunne ikke gennemføres. validationStatus=validationNotPossible"
      type: object
      required:
        - validationStatus
        - reason
      properties:
        validationStatus:
          type: string
        reason:
          description: "Årsag til at valideringen ikke er mulig"
          type: string
          enum:
            - ExistingDrugMedicationsRequired

    validationFailed:
      description: "Valideringen fejlede. validationStatus=validationFailed"
      type: object
      required:
        - validationStatus
        - validationErrors
      properties:
        validationStatus:
          type: string
        validationErrors:
            description: "Liste af valideringsfejl"
            type: array
            items:
                $ref: "#/components/schemas/validationError"

    validationError:
      description: "Detaljer om valideringsfejl"
      allOf:
        - $ref: "#/components/schemas/Error"
        - type: object
          required:
            - elementPath
            - clause
          properties:
            elementPath:
              description: "Element path for det validate element der fejlede valideringen"
              type: string
            clause:
              $ref: "#/components/schemas/clause"

    clause:
      type: object
      required:
        - code
        - text
        - message
      properties:
        code:
          description: "Klausulkoden for medicintilskud"
          type: string
        text:
          description: "Tekst for klausulen"
          type: string
        message:
          description: "Beskeden som er indtastet under oprettelses af en klausul"
          type: string

    Error:
      type: object
      required:
        - message
        - code
      properties:
        message:
          $ref: "./common.yaml#/components/schemas/ErrorMessage"
        code:
          $ref: "#/components/schemas/ErrorCode"

    ErrorCode:
      description: "Fejlkode for fejlet validering"
      type: integer
      example: 10908