openapi: 3.0.1
info:
  title: Validation Component
  description: ""
  version: "1.0.0"
  contact:
    email: "development@kvalitetitsit.dk"
tags:
  - name: validation
    description: "API til at validere lægemiddelordinationer fra FMK (fælles medicin kort)"
servers:
  - url: '{protocol}://{environment}:{port}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      environment:
        enum:
          - localhost # Docker-compose setup
        default: localhost # Development
      port:
        enum:
          - "8080"
        default: "8080"
paths:
  /2025/08/01/validate:
    post:
      tags:
        - validation
      description: "Validerer lægemiddelordinationener fra FMK"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/validationRequest'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/validationResponse'
            text/plain:
              schema:
                type: string
        '400':
          $ref: '#/components/responses/400'

components:
  responses:
    '400':
      description: "Bad Request"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/basicError'

  schemas:
    basicError:
      type: object
      required:
        - timestamp
        - status
        - error
        - path
      properties:
        error:
          description: Error message
          type: string
        path:
          description: Path
          type: string
        status:
          description: HTTP status code
          type: integer
        timestamp:
          description: Time of error
          type: string
          format: date-time

    validationRequest:
      type: object
      required:
        - skipValidations
        - personIdentifier
        - age
        - validate
      properties:
        skipValidations:
          description: "Koder for fejltyper som skal tilsidesættes ved validering"
          type: array
          items:
            $ref: "#/components/schemas/validationCode"
        personIdentifier:
          description: "Unikt id svarende til CPR medicinkortets id, CPR-nummer eller eCPR-nummer, disse værdier medsendes ikke, da data i kaldet dermed er pseudonymiseret. Det skal være muligt at finde tilbage til CPR-nummer eller eCPR-nummer ved opslag i FMK, f.eks. ved fejlsøgning"
          type: string
          example: "1234567890"
        age:
          description: "Patientens/borgerens alder"
          type: integer
          example: 62
          minimum: 0
        validate:
          description: "Data der skal valideres"
          type: array
          items:
            $ref: "#/components/schemas/validate"
        existingDrugMedications:
          description: "Eksisterende lægemiddelordinationer i FMK. En tom liste betyder at sådanne data ikke findes. Mangler feltet, er data bevidst ikke sendt med"
          type: array
          nullable: true
          items:
            $ref: "#/components/schemas/existingDrugMedication"

    validationCode:
      description: "Fejlkode for fejlet validering"
      type: integer
      example: 10908

    validate:
      description: "Data der skal valideres"
      type: object
      required:
        - action
        - elementPath
        - newDrugMedication
      properties:
        action:
          description: "Handlingen der kræver validering"
          type: string
          enum:
            - CreateDrugMedication
            - UpdateDrugMedication
            - CreatePrescription
          example: CreateDrugMedication
        elementPath:
          description: "FMK’s element path i udvidet valideringer"
          type: string
          example: CreateDrugMedicationRequest.DrugMedication[2]
        newDrugMedication:
            $ref: "#/components/schemas/newDrugMedication"

    newDrugMedication:
      description: "Data fra lægemiddelordinationen som skal valideres"
      type: object
      required:
        - createdBy
        - createdDateTime
        - drugIdentifier
        - indicationCode
      properties:
        createdBy:
          description: "Aktør der har oprettet lægemiddelordinationen"
          $ref: "#/components/schemas/actor"
        reportedBy:
          description: "Aktør der har rapporteret lægemiddelordinationen"
          $ref: "#/components/schemas/actor"
        createdDateTime:
          description: "Dato og tid for oprettelse af lægemiddelordinationen"
          type: string
          format: date-time
          example: "2025-06-13T14:24:03+02:00"
        drugIdentifier:
          description: "Lægemidlets drugid. Kilde er foreløbigt altid Medicinpriser"
          type: long
          example: "28100902676"
        indicationCode:
          description: "Indikationen som angivet ved oprettelse af ordinationen. Kilde er altid Medicinpriser"
          type: string
          example: "31"

    actor:
      description: "Aktør for lægemiddelordinationen"
      type: object
      properties:
        specialityCode:
          description: "Lægens speciale jf. autorisationsregistret"
          type: string
          example: "PSYK"
        organisationSpeciality:
          description: "Organisationens speciale jf. SOR"
          type: string
          example: "psykiatri"

    existingDrugMedication:
      description: "Udvalgte data for lægemiddelordinationer i FMK, inklusiv tidligere versioner"
      type: object
      required:
        - drugIdentifier
        - atcCode
        - formCode
        - routeOfAdministrationCode
      properties:
        drugIdentifier:
          description: "Lægemidlet drugid, uanset kilde (dvs. f.eks. også magistrelle lægemidler)"
          type: long
          example: "28100645874"
        atcCode:
          description: "ATC-kode. Kilde er altid Medicinpriser"
          type: string
          example: "J01CE02"
        formCode:
          description: "Lægemidlets form-kode. Kilde er altid Medicinpriser"
          type: string
          example: "TABFILM"
        routeOfAdministrationCode:
          description: "Administrationsvejskode, som angivet på lægemiddelordinationen ved ordination. Kilde er altid Medicinpriser"
          type: string
          example: "OK"


    validationResponse:
      type: object
      oneOf:
        - $ref: '#/components/schemas/validationSuccess'
        - $ref: '#/components/schemas/validationNotPossible'
        - $ref: '#/components/schemas/validationFailed'
      discriminator:
        propertyName: validationStatus
        mapping:
          validationSuccess: '#/components/schemas/validationSuccess'
          validationNotPossible: '#/components/schemas/validationNotPossible'
          validationFailed: '#/components/schemas/validationFailed'

    validationSuccess:
      description: "Valideringen er gennemført uden fejl. validationStatus=validationSuccess"
      type: object
      required:
        - validationStatus
      properties:
        validationStatus:
            type: string

    validationNotPossible:
      description: "Valideringen kunne ikke gennemføres. validationStatus=validationNotPossible"
      type: object
      required:
        - validationStatus
        - reason
      properties:
        validationStatus:
          type: string
        reason:
          description: "Årsag til at valideringen ikke er mulig"
          type: string
          enum:
            - ExistingDrugMedicationsRequired

    validationFailed:
      description: "Valideringen fejlede. validationStatus=validationFailed"
      type: object
      required:
        - validationStatus
        - validationErrors
      properties:
        validationStatus:
          type: string
        validationErrors:
            description: "Liste af valideringsfejl"
            type: array
            items:
                $ref: "#/components/schemas/validationError"

    validationError:
      description: "Detaljer om valideringsfejl"
      type: object
      required:
        - errorCode
        - errorMessage
        - elementPath
        - clauseCode
        - clauseText
        - warningQuestion
      properties:
        errorCode:
          $ref: "#/components/schemas/validationCode"
        errorMessage:
          description: "Fejlbesked for valideringen"
          type: string
        elementPath:
          description: "Element path for det validate element der fejlede valideringen"
          type: string
        clauseCode:
          description: "Klausulkoden for medicintilskud"
          type: string
        clauseText:
          description: "Tekst for klausulen"
          type: string
        warningQuestion:
          description: "Tekst egnet til præsentation i LPS, EPJ-system mm."
          type: string








