services:
  validation-db:
    image: mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=hellodb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret1234
    healthcheck:
      test: mysql --user=root --password=rootroot -e 'show databases;'
      interval: 2s
      timeout: 2s
      retries: 10
    ports:
      - 3306:3306
    volumes:
      - ../configuration/ddl:/docker-entrypoint-initdb.d

  master-db:
    image: trifork/tilskud-sdm-db:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=sdm_krs_a
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret1234
    healthcheck:
      test: mysql -e 'show databases;'
      interval: 2s
      timeout: 2s
      retries: 10

  validation-component:
    image: kvalitetsit/klausuleret-tilskud-valideringskomponent:latest
    environment:
      - app_jdbc_validation_url=jdbc:mariadb://validation-db:3306/hellodb
      - app_jdbc_validation_username=user
      - app_jdbc_validation_password=secret1234
      - app_jdbc_master_url=jdbc:mariadb://master-db:3306/sdm_krs_a
      - app_jdbc_master_username=root
      - app_jdbc_master_password=
      - usercontext_header_name=X-Test-Auth
      - userattributes_role_key=UserRoles
      - userattributes_org_key=organisation
      - userrole_admin_values=adminrole
      - userrole_user_values=userrole1,userrole2
      - userrole_monitor_values=monitorrole
      - userrole_provisioner_values=provisionerrole
    depends_on:
      validation-db:
        condition: service_healthy
      master-db:
        condition: service_healthy
    ports:
      - 8080:8080
      - 8081:8081

  documentation-and-test:
    image: kvalitetsit/klausuleret-tilskud-valideringskomponent-documentation:latest
    environment:
      - BASE_URL=/test
      - 'SERVER_URLS=[{"url": "http://localhost:8080", "name": "HelloService"}]'
    ports:
      - 80:8080
