services:
  mariadb:
    image: mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=hellodb
      - MYSQL_USER=hellouser
      - MYSQL_PASSWORD=secret1234
    healthcheck:
      test: mysql --user=hellouser --password=secret1234 -e 'show databases;'
      interval: 2s
      timeout: 2s
      retries: 10

  flyway:
    image: flyway/flyway:latest
    environment:
      - FLYWAY_URL=jdbc:mariadb://mariadb:3306/hellodb
      - FLYWAY_USER=hellouser
      - FLYWAY_PASSWORD=secret1234
    volumes:
      - ../configuration/ddl:/flyway/sql
    depends_on:
      mariadb:
        condition: service_healthy
    command: migrate

  validation:
    image: kvalitetsit/klausuleret-tilskud-valideringskomponent:latest
    environment:
      - jdbc_url=jdbc:mariadb://mariadb:3306/hellodb
      - jdbc_user=hellouser
      - jdbc_pass=secret1234
      - usercontext_header_name=X-Test-Auth

      - userattributes_role_key=UserRoles
      - userattributes_org_key=organisation

      - userrole_admin_values=adminrole
      - userrole_user_values=userrole1,userrole2
      - userrole_monitor_values=monitorrole
      - userrole_provisioner_values=provisionerrole
    depends_on:
      mariadb:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    ports:
      - 8080:8080

  validation-qa:
    image: local/klausuleret-tilskud-valideringskomponent-qa:dev
    volumes:
      - /tmp:/jacoco-output
    environment:
      JVM_OPTS: -javaagent:/jacoco/jacocoagent.jar=output=file,destfile=/jacoco-output/jacoco-it.exec,dumponexit=true -cp integrationtest.jar
      LOG_LEVEL: "INFO"
      JDBC_URL: "jdbc:mariadb://mariadb:3306/hellodb"
      JDBC_USER: "hellouser"
      JDBC_PASS: "secret1234"
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      default:
        aliases:
          - klausuleret-tilskud-valideringskomponent
    # Healthcheck mimics Wait.forHttp("/actuator").forPort(8081)
    healthcheck:
      test: [ "CMD", "sh", "-c", "curl -f http://localhost:8081/actuator || exit 1" ]
      interval: 5s
      timeout: 2s
      retries: 10

  documentation-and-test:
    image: kvalitetsit/klausuleret-tilskud-valideringskomponent-documentation:latest
    environment:
      - BASE_URL=/test
      - 'SERVER_URLS=[{"url": "http://localhost:8080", "name": "HelloService"}]'
    ports:
      - 80:8080
