services:
  itukt-db:
    image: mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=itukt_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret1234
    healthcheck:
      test: mysql --user=root --password=rootroot -e 'show databases;'
      interval: 2s
      timeout: 2s
      retries: 10
    ports:
      - 3306:3306
    volumes:
      - ../configuration/ddl:/docker-entrypoint-initdb.d

  stamdata-db:
    image: trifork/tilskud-sdm-db:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=sdm_krs_a
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret1234
    healthcheck:
      test: mysql -e 'show databases;'
      interval: 2s
      timeout: 2s
      retries: 10
    
  validation-component:
    image: kvalitetsit/klausuleret-tilskud-valideringskomponent:latest
    environment:
      - ITUKT_COMMON_ITUKTDB_URL=jdbc:mariadb://itukt-db:3306/itukt_db
      - ITUKT_COMMON_ITUKTDB_USERNAME=user
      - ITUKT_COMMON_ITUKTDB_PASSWORD=secret1234
      - ITUKT_VALIDATION_STAMDATA_STAMDATADB_URL=jdbc:mariadb://stamdata-db:3306/sdm_krs_a
      - ITUKT_VALIDATION_STAMDATA_STAMDATADB_USERNAME=root
      - ITUKT_VALIDATION_STAMDATA_STAMDATADB_PASSWORD=
      - JVM_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    depends_on:
      itukt-db:
        condition: service_healthy
      stamdata-db:
        condition: service_healthy
    ports:
      - 8080:8080
      - 8081:8081
      - 5005:5005

  documentation-and-test:
    image: kvalitetsit/klausuleret-tilskud-valideringskomponent-documentation:latest
    environment:
      - BASE_URL=/openapi
      - 'SERVER_URLS=[{"url": "http://localhost:8080", "name": "validation"}]'
    ports:
      - 80:8080
